name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Vue.js dependencies
        working-directory: ./
        run: npm install

      - name: Install Node.js dependencies
        working-directory: ./service
        run: npm install

      - name: Run Node.js server
        working-directory: ./service
        run: nodemon authService &

      - name: Wait for server to start
        run: sleep 10

      - name: Run Vue.js tests
        working-directory: ./
        run: npm run test:e2e
